- geoapi/services/notifications.py
- geoapi/tasks/external_data.py
- geoapi/tasks/lidar.py
- geoapi/tests/conftest.py
- geoapi/tests/external_data_tests/test_external_data.py
- geoapi/utils/decorators.py
Add rollback to worker tasks
* [DES-9999](https://jira.tacc.utexas.edu/browse/DES-9999)
* Add rollback to worker tasks
* Rollback on any unhandled exceptions in observable projects
* Add related unit tests to check for rollback
Completed since last time we discussed this
> Add rollingback to worker tasks

- geoapi/routes/projects.py
- geoapi/services/projects.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/api_tests/test_projects_service.py
This adds a handle to PUT requests to enable update functionality for projects in the backend.
This was mainly needed to implement updating for a project's name and description from the user panel. 
* [DES-1676](https://jira.tacc.utexas.edu/browse/DES-1676)
I've created new update methods for the project service and route. 
Furthermore, I've tried to implement test for the corresponding methods.
1. Run tests.
> DES-1676 - Add update functionality to individual projects.

- geoapi/routes/projects.py
- geoapi/services/projects.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/api_tests/test_projects_service.py
- geoapi/tests/api_tests/test_users_service.py
- geoapi/tests/conftest.py
Support querying of projects by UUID
* [DES-1899](https://jira.tacc.utexas.edu/browse/DES-1899)
The `GET` for `/projects` now supports a query parameter `uuid`.  So you can request a list of uuids instead of getting all the projects (e.g. `/projects/?uuid=12345567777` to get one project  or `/projects/?uuid=12345567777,ABCDEFGHIG` to get multiple)
1. Run unit tests
2. (optional) make queries to local server
> Task/DES-1899 support querying projects by UUID

- .travis.yml
Travis's CI deploy/script has to be a one line command. See travis-ci/dpl#673
_None_
> hotfix:  travis's CI deploy/script has to be a one line command

- Makefile
- geoapi/routes/__init__.py
- geoapi/routes/projects.py
- geoapi/routes/public_projects.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/api_tests/test_public_projects_routes.py
Add /public-projects routs (a duplicate GETs in /projects) to be provided by WSO2 (auth_type:none) for guest users
* [DES-1946](https://jira.tacc.utexas.edu/browse/DES-1946)
* Fix so that swagger.json can be provided.
* Return 403 for unauthed projects listing
* Provide project routes for public access
1. see swagger/openapi definition (http://localhost:8888/swagger.json or on staging) and confirm that everything looks right for public-projects
2. testing staging environment that has been configured with auth type of None for these routes.
We need to test on staging environment using WS
> Des 1946 provide public routes

- .travis.yml
- kube/Makefile
This PR updates deployment steps:
* removes use of travis-ci to push images to dockerhub (not being done in Jenkins https://jenkins01.tacc.utexas.edu/view/Hazmapper+Geoapi/)
* Also removes use of latest-container as cache for building container (for testing purposes)
* fixes issue where kubectl apply wasn't using the correct prod/staging kube context.
* [DES-1950](https://jira.tacc.utexas.edu/browse/DES-1950)
> Des 1950 update deployment

- geoapi/services/projects.py
- geoapi/tasks/external_data.py
- geoapi/utils/agave.py
Removes saving files on export.
Related to TACC-Cloud/hazmapper#70, which moves the functionality to the frontend.
* [DES-1988](https://jira.tacc.utexas.edu/browse/DES-1988)
Deleted `postFile`/`deleteFile` calls and definitions.
1. Test with TACC-Cloud/hazmapper#70 to ensure that saving still work in the frontend.
> Task/DES-1988: Delete saving file on export.

- geoapi/utils/agave.py
This is a workaround for bug documented in
* https://jira.tacc.utexas.edu/browse/CS-169
* https://jira.tacc.utexas.edu/browse/DES-2084
Sometimes a 403 is returned by tapis sometimes using the prod tenant
instead of the designsafe tenant. The workaround is to use the service
account on the designsafe tenant (which somehow "fixes" the problem in case someone tries to access the file again later)
* [DES-2084](https://jira.tacc.utexas.edu/browse/DES-2084)
1.  Using main branch (or prod or staging)
2. Try to import Photo 262_ARL.jpg from "/PRJ-2714/Data Sets by Location/Guanica Buildings/Images/Geotagged Images/”
3. It should fail due to 403
4. Use this PR's branch to do step 2
5. It should work and you should see some warnings in the logs saying that we are using the service account
6. Try …
> Use service account to download file

- geoapi/services/projects.py
Changed db query to allow multiple asset parameters instead of a single one at a time.
* [DES-2185](https://jira.tacc.utexas.edu/browse/DES-2185)
Modified the sql query to adjust to multiple asset type selection.
1. Test with TACC-Cloud/hazmapper#82
2. Ensure that the everything is properly filtered.
> Bug/DES-2185: Fix filtering query.

- geoapi/tasks/external_data.py
- geoapi/tasks/lidar.py
Use `point_cloud`'s `description` instead of the `feature`'s `id`.
Also, fix bug in `tasks/lidar.py` where `celery_uuid` is not imported.
* [DES-2216](https://jira.tacc.utexas.edu/browse/DES-2216)
1. Ensure the `description` of `point_cloud` is being used as asset name in `asset-panel`
Long-term I think we could have the private feature property to contain this information.
However, I think this is ok because we don't lose `description` data.
> Task/DES-2216: Use description for point cloud asset name instead of ID.

- .github/workflows/main.yml
- README.md
- docker-compose.test.yml
- docker-compose.yml
- geoapi/tests/api_tests/test_notifications_routes.py
- geoapi/tests/api_tests/test_streetview_routes.py
- geoapi/tests/api_tests/test_streetview_service.py
This is the first step to bringing back CI since we stopped using Travis-CI. 
This only adds unit tests checking the routes (see Summary of Changes for other test-related tweaks). As a follow-up, I would create PRs this month or next month to add flake8 [DES-2266](https://jira.tacc.utexas.edu/browse/DES-2266)
This PR:
* fixes some tests
* skips some failing test (follow on work in [DES-2264](https://jira.tacc.utexas.edu/browse/DES-2264) and [DES-2265](https://jira.tacc.utexas.edu/browse/DES-2265)
* adds github actions to run tests
* Adds a testing docker compose to help run tests locally.  Steps are added into Readme.
* Add workflow for github actions
* Fix Streetview routes tests that got out of line with the latest changes to Streetview
* Skip failing tests and add related JIRA issues …
> Task/DES-2262: use github actions for unit testing

- kube/geoapi.yaml
Bump worker memory to 100GB. 
* [DES-2211](https://jira.tacc.utexas.edu/browse/DES-2211)
1.  Probably best to test later in the staging environment.
> task/DES-2211: Increase memory limit for worker pods

- geoapi/tests/utils_tests/test_agave.py
- geoapi/utils/agave.py
Fix regression (caused by #99)  where the service account was using the wrong URL for getting files.
* [DES-2374](https://jira.tacc.utexas.edu/browse/DES-2374)
1. On prod/staging, try to import a file on My Data and confirms it fails
2. Use this branch locally, and then try to import one of those failing files.
> task/DES-2374: fix service account url for getting files

- geoapi/services/projects.py
- geoapi/tasks/__init__.py
- geoapi/tasks/projects.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/api_tests/test_projects_service.py
- geoapi/tests/conftest.py
Moving project assets deletion to celery
* [DES-9999](https://jira.tacc.utexas.edu/browse/DES-9999)
1.  Do a project deletion and confirm that the project is deleted and done in a celery task
**Background**:
The deletion work from the route should be moved to celery as it can take awhile (especially with poetry pointcloud files in a project) **but** it seems to cause a worse problem where just 4 project deletions can block the 4 workers in gunicorn.  It looks like it is something like this issue:  https://www.aboutwayfair.com/tech-innovation/blocking-io-in-gunicorn-gevent-workers  (in our case something in `shutil.rmtree` is blocking IO that gevent can't handle and blocks the workers 🤷‍♂️ ). (in addition to gunicorn docs, I found this overview helpful …
> task/DES-abc: Move project asset directory deletion to celery task

- geoapi/custom/designsafe/project_users.py
- geoapi/models/project.py
- geoapi/models/users.py
- geoapi/services/projects.py
- geoapi/services/users.py
- geoapi/tasks/external_data.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/api_tests/test_projects_service.py
- geoapi/tests/api_tests/test_users_service.py
- geoapi/tests/custom/test_designsafe.py
- geoapi/utils/agave.py
Fixes bugs related to determining if projects are delectable
* Fixes response for project creation ([DES-2381](https://jira.tacc.utexas.edu/browse/DES-2381))
* Fixes incorrect determination of `deletable` for getting/listing projects [DES-2366](https://jira.tacc.utexas.edu/browse/DES-2366)
* [DES-2366](https://jira.tacc.utexas.edu/browse/DES-2366)
* [DES-2381](https://jira.tacc.utexas.edu/browse/DES-2381)
1.  Test in staging
2. Ensure that create projects endpoint have `delectable` response
3. Ensure that created projects have the write deletable status depending on the users status in the project (did they create it or are they a pi/copi).
> task/DES-2381:  fix created project's response to include deletable

- .flake8
- .github/workflows/main.yml
- geoapi/settings.py
- geoapi/tasks/streetview.py
- geoapi/tests/tasks_tests/test_streetview.py
- geoapi/tests/utils_tests/test_agave.py
- geoapi/utils/agave.py
- geoapi/utils/streetview.py
This PR fixes two issues that are affecting the use of importing files to mapillary:
* [WG-66](https://jira.tacc.utexas.edu/browse/WG-66). Fixes the path to mapillary tools
* [WG-36](https://jira.tacc.utexas.edu/browse/WG-36). Use a consistent way to get files from tapis systems. The standalone `getRawFileToPath`(previously used by streetview) is replaced with the `getFile` method which is used in other places and (especially since https://github.com/TACC-Cloud/geoapi/pull/99) provides a fault-tolerant approach for retrieving files
* some linting changes to `geoapi/tasks/streetview.py`
* [WG-36: Review getRawFileToPath after DES-2236 work-around](https://jira.tacc.utexas.edu/browse/WG-36)
* [WG-66: Fix path of mapillary_tools](https://jira.tacc.utexas.edu/browse/WG-66)	
1.  Deployed to …
> Task/WG-66-and-WG-36: fix path to mapillary tools and improve getting files from tapis

- geoapi/tasks/external_data.py
Add missing rollback in case of a failed database connection occurs when getting list of observable projects 
* [WG-130](https://jira.tacc.utexas.edu/browse/WG-130)
1) one could add a `raise Exception()`
2) and then alter `geoapi/celery_app.py` so the refresh task occurs every minute
3) then confirm things in local logs'
> task/WG-130: Add missing rollback in case of failed database connection

- kube/utils/backup_staging_production_to_ranch.sh
Update the backup script to ensure pods are running before the backup/ssh begins. Discussions in thread [here](https://tacc-team.slack.com/archives/C04TMKBDS1X/p1693113790448049):
Fixes issue seen in failed [jenkins job ](https://tacc-team.slack.com/archives/C04TMKBDS1X/p1693113790448049).
Running in currently in this [jenkins job](https://jenkins01.tacc.utexas.edu/job/Geoapi%20(assets%20backup)/376/).
N/A
> Update script to ensure pods are RUNNING

- kube/Makefile
- kube/geoapi.yaml
The PR removes vestigial geoapi-postgres from kube workflow now that we have dedicated database vm.
> hotfix: remove vestigial geoapi-postgres from kube workflow

- devops/geoapi-services/docker-compose.yml
- devops/geoapi-workers/docker-compose.yml
Add missing syslog to docker-compose
* [WG-178](https://jira.tacc.utexas.edu/browse/WG-178)
preparing to deploy to `dev` to ensure that is all that is missing.
> task/WG-178:  Add missing syslog to docker-compose

- devops/geoapi-services/docker-compose.yml
- devops/geoapi-workers/docker-compose.yml
Add `restart: always` to docker compose
I noticed that this was missing  when the prod worker machine was offline.
> hotfix: Add restart to docker compose

- geoapi/services/features.py
- geoapi/tasks/external_data.py
- geoapi/tasks/streetview.py
- geoapi/tests/external_data_tests/test_external_data.py
- geoapi/tests/utils_tests/test_features.py
- geoapi/utils/agave.py
- geoapi/utils/features.py
This PR adds support the scraping of questionnaires. It ensures the questionnaires in connected projects are scraped and that any asset images aren't inadvertently scrapped twice.
This PR also:
* refactors how we determine which files to scrape
* removes audio file formats that were not used
* [WG-170](https://jira.tacc.utexas.edu/browse/WG-170)
1. Use hazmapper's `feature/questionnaire` when running hazmapper
2. Create a new map and select top level dir of shared project "Questionnaire_Example".  ensure "Sync Folder" is checked. (See screenshot below)
3. Click "Submit"
4. See that one questionnaire is imported correctly. and that its asset images aren't incorrectly imported as individual assets.
5. Note that there will be some log errors as there are some questionnaire files in the /Rapp …
> task/WG-170: fix scraping of questionnaire

- geoapi/utils/decorators.py
- geoapi/utils/users.py
Add uuid for guest users
* [WG-139](https://jira.tacc.utexas.edu/browse/WG-139)
1. To be tested with the corresponding hazmapper branch
2. Create a map
3. Make it public and copy link
4. Open icognito window
5. Go to public link
6. Look at geoapi logs to see that username now has a uuid for the guests (e.g.  `Get features of project:2 for user:Guest_5669ae1c-a292-4bf2-b09b-fc63d6f86e10`)
> task/WG-139: add uuid for guest users

- devops/geoapi-services/nginx.conf
Add preflight requests for assets route.  This was in the kube nginx conf but missed it in the transition to VMs.  
Currently, this is breaking our questionnaire work: 
None
1. Deployed via https://github.com/TACC-Cloud/wma-geospatial-deployments/commit/a2704a5484f1c0daf57ea099f53c34b1b078a468 to staging: https://hazmapper.tacc.utexas.edu/staging/
https://github.com/TACC-Cloud/geoapi/pull/157/files#r1385415551 comment should be considered here.  I think so many examples have such a long cache time for **"preflight requests"** is cause "why not" but then chrome or the browser might choose a lower time.
* https://enable-cors.org/server_nginx.html
* https://stackoverflow.com/questions/15381105/what-is-the-motivation-behind-the-introduction-of-preflight-cors-requests
> Add handling of preflight requests in assets

- devops/Dockerfile.worker
LASTools is failing at the moment in our Dockerfile.  We no longe run lasinfo to read crs from las files (we use pdal now for that).  So we no longer need this step and can just remote it.
None
> hotfix: remove LAStools building step

- geoapi/routes/projects.py
Improve logging of delete to include UUID with project ID. See notes of the related [WG-70](https://jira.tacc.utexas.edu/browse/WG-70) issue of why this is needed. 
In https://github.com/TACC-cloud/geoapi
in geoapi/routes/projects.py
* [WG-182](https://jira.tacc.utexas.edu/browse/WG-182)
- Improved logging of delete to include UUID
1. Navigate to geoapi repo and run 'make start'
2. Run this command 'curl -H X-JWT-Assertion-designsafe:$JWT localhost:8000/projects/' to list the current projects
3. Pick a project that's ok to delete and use its projectid in this next command
4. curl -X 'DELETE' \\
'http://localhost:8000/projects/1/' \\
-H X-JWT-Assertion-designsafe:$JWT
5. Should get a 'status': 'ok' response from api
6. Run this command again 'curl -H X-JWT-Assertion-designsafe:$JWT …
> task/WG-182: adding additional logging for project uuid upon deletion

- README.md
- geoapi/utils/decorators.py
Add jwt verification to geoapi
* [WG-67](https://jira.tacc.utexas.edu/browse/WG-67)
- Before in our ReadMe file we were obtaining a JWT manually through an external site. This JWT was using the HS256 algorithm. We were not requiring it to be verified.
- Using the same JWT (from external site) was a problem when adding verification bc we were using two different algorithms (HS256 and RS256). Since the pub_key and token are different algorithms, this would cause the decoding to fail when attempting verification. 
- In order to fix this I changed the algorithm we were decoding with to be RS256 to match the pub key
- With these changes, this requires the devs to obtain their real JWT (which is also RS256). Instructions on how to get this will be provided, if you don't have this already.
- I …
> task/WG-67: Adding JWT verification

- .github/pull_request_template.md
Updating PR template links to use the new cloud system links
* [WG-194](https://tacc-main.atlassian.net/browse/WG-194)
- Changed the link in the templates to use the new cloud system links
1. When creating a PR, check the template and make sure the new link format (under "Related Jira Tickets") is correct with the new cloud system link
> task/WG-194: GeoAPI PR Template Updated Links

- geoapi/models/project.py
- geoapi/routes/projects.py
- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/tests/conftest.py
- geoapi/utils/decorators.py
This PR adds the following additional information to logs for analytics on the `features` endpoint:
* application information (i.e. "taggit", "hazmapper")
*  DesignSafe project information (e.g. "project-8131157524548227566-242ac117-0001-012" which is tapis system name of DesignSafe project)
* is this route being used for the public view of a map
Here are (**updated example on Dec 8th**) examples.
Taggit:
```
Get features of project for user:nathanf application:hazmapper public_view:False project_uuid:a5114ec8-030b-4cff-aa01-1a4a05d1cb88 project:6 tapis_system_id:designsafe.storage.default tapis_system_path:/nathanf
````
Hazmapper (logged in and private map):
```
Get features of project for user:nathanf application:hazmapper public_view:False …
```
> task/WG-138-WG-140: improve logs for analytics to include application and related DS system

- geoapi/custom/__init__.py
- geoapi/custom/designsafe/project.py
- geoapi/custom/designsafe/project_users.py
- geoapi/services/features.py
- geoapi/services/projects.py
- geoapi/tasks/external_data.py
- geoapi/tasks/streetview.py
- geoapi/tests/conftest.py
- geoapi/tests/custom/designsafe/test_project.py
- geoapi/tests/custom/designsafe/test_project_users.py
- geoapi/tests/utils_tests/test_agave.py
- geoapi/utils/agave.py
- geoapi/utils/tenants.py
use tapisv3 for file-delete and file-create operations for project creation
* [WG-263](https://tacc-main.atlassian.net/browse/WG-263)
1. Create a project on My Data using angular hazmapper from this branch https://github.com/TACC-Cloud/hazmapper/pull/214
> task/WG-263: use tapisv3 for file-delete and file-create operations for project creation

- geoapi/services/features.py
- geoapi/services/images.py
- geoapi/tasks/external_data.py
- geoapi/tests/api_tests/test_feature_service.py
- geoapi/tests/conftest.py
- geoapi/tests/external_data_tests/test_external_data.py
- geoapi/tests/fixtures/tapis_meta_no_geolocation.json
- geoapi/tests/fixtures/tapis_meta_with_geolocation.json
- geoapi/tests/services/test_image_service.py
- geoapi/tests/utils_tests/test_geo_location.py
- geoapi/utils/additional_file.py
- geoapi/utils/agave.py
- geoapi/utils/features.py
- geoapi/utils/geo_location.py
This PR:
* addresses WG-211/DES-2636 by searching by file name to get tapis file metadata. This mimics how DS gets tapis file metadata.  All changes for this are in `geoapi/utils/agave.py`
* uses tapis file metadata created by RApp during file image imports (WG-39). Previously, this was only done when scraping files and if the field were within the the Rapp subfolder. Now users can manually import files using metadata and they no longer have to be located in the Rapp subfolder for tapis-metadata to be used.
All changes in this PR (besides those in  `geoapi/utils/agave.py`) are related to bullet point 2.  With these changes, now we get tapis metadata on all images being imported and use the location information there if it exists.  Otherwise, we use the image file's exif data.
* …
> task/WG-211 update metadata query to support DES-2636

- README.md
- devops/docker-compose.local.yml
- devops/geoapi-services/docker-compose.yml
- devops/geoapi-workers/docker-compose.yml
- geoapi/custom/designsafe/project.py
- geoapi/exceptions.py
- geoapi/settings.py
- geoapi/tasks/external_data.py
- geoapi/tests/custom/designsafe/test_project.py
- geoapi/tests/custom/designsafe/test_project_users.py
- geoapi/tests/external_data_tests/test_external_data.py
- geoapi/tests/fixtures/tapis_meta_no_geolocation.json
- geoapi/tests/fixtures/tapis_meta_with_geolocation.json
- geoapi/tests/utils_tests/test_agave.py
- geoapi/tests/utils_tests/test_geo_location.py
- geoapi/utils/agave.py
- geoapi/utils/geo_location.py
Use file-metadata routes from DesignSafe.
This PR also:
* Removes the use of service accounts bc814bd410e66eec5a10c3a67c2cb5f088bc9cbd
* Adds some testing notes to Readme 71c1a0bbb16cd4a74f4139b1ee9527a3a69b560d
* [WG-254](https://tacc-main.atlassian.net/browse/WG-254)
0. Update `.env` from https://stache.utexas.edu/entry/892c730561534ed3b3d306dbf933455d so that you have new DESIGNSAFE_URL env variable.
2. Run this branch locally
3. Run `feature/tapisv3` hazmapper locally using  `backend: EnvironmentType.Local` in `angular/src/environments/environment.ts`
4. Make a map and add images `image.jpg` and `image_with_geolocation_tapis_metadata3.jpg
` from https://designsafeci-next.tacc.utexas.edu/data/browser/projects/PRJ-4576/workdir
5. Watch logs tosee that file metadata …
> task/WG-254: use file-metadata routes from DesignSafe

- geoapi/routes/status.py
- geoapi/tests/api_tests/test_status_routes.py
Change `/status/` endpoint so that it no longer requires authentication
I want to add backends directly to our monitoring due to the weird behavior we saw with `experimental.geoapi-services` yesterday
> hotfix:  change status endpoint to no longer require authentication

- geoapi/custom/designsafe/project.py
- geoapi/routes/__init__.py
- geoapi/utils/agave.py
Fix use of DS's project metadata endpoint on map-project creation/deletion.
https://github.com/TACC-Cloud/geoapi/pull/199 was missing the changes to the header 
(at that time things were not deployed to ds-next so missed that)
* [WG-296](https://tacc-main.atlassian.net/browse/WG-296)
1. Create a map connected to a project
2. Check geoapi logs to see that no exceptions occurred
3. Delete that map
4. Check geoapi logs to see that no exceptions occurred
> task/WG-296: fix projects meta endpoint usage

- geoapi/custom/designsafe/project_users.py
- geoapi/tests/fixtures/designsafe_api_project.json
Handle guest users in v3 DesignSafe projects 
* [WG-311](https://tacc-main.atlassian.net/browse/WG-311)
1.  Create project on DS-Next where there is a guest user
2. Confirm that you can create a hazmapper map project for that DS project. Confirm the right users show up and no errors in log during map creation.
> task/WG-311: handle guest users

- geoapi/tasks/external_data.py
- geoapi/tests/external_data_tests/test_external_data.py
We want to skip the scraping of trash files.  Now top-level trash directories have a path of `.Trash` instead of `./Trash`.  This PR updates our logic when scraping files.
> hotifx: trash is being scraped in TAPIS-v3

- geoapi/routes/auth.py
Add hazmapper.local to client_urls.  Now angular` `http://hazmapper.local:4200/` will work via `npm run start:local`.
> hotfix:  Add hazmapper.local to client_urls

- Makefile
Fix makefile so we don't push a `latest` tagged image to dockerhub.  Pushing of latest images is handled by [jenkins job ](https://jenkins.portals.tacc.utexas.edu/view/Hazmapper%20+%20Geoapi/job/Geoapi%20(build%20image)/configure)which pushes latest only when on main branch.
This was causing issues as we have some automatic deployment (via watchtower) of the latest on the dev environment, which would sometimes break when non-main images were pushed.
None
> hotfix: stop deploying latest as Jenkins handles that for main branch building

- devops/utils/backup_staging_production_to_ranch.sh
Free up some backup space
* by removing backups older than 2 weeks of **staging** data (instead of 6 weeks) before creating a new backup 
* by removing backups older than 4 weeks of **production** data (instead of 6 weeks) before creating a new backup
See https://tacc-team.slack.com/archives/C04TMKBDS1X/p1735829948900709?thread_ts=1735829239.120209&cid=C04TMKBDS1X
> hotfix: keep only 2 weeks of staging backups

- devops/docker-compose.local.yml
This PR changes the local dev docker compose so that we have a single worker service for each queue. So now instead of one worker service running celery twice, we have a service for the heavy queue and a service for the default queue.
In https://github.com/TACC-Cloud/geoapi/pull/220, we added a heavy queue.  Two comments at the time were about
* how the celery tasks was running twice and not in foreground in the worker service https://github.com/TACC-Cloud/geoapi/pull/220#discussion_r1824957416
* how we couldn't see in the logs the queue being run on: https://github.com/TACC-Cloud/geoapi/pull/220#discussion_r1825055954
1. Confirm you can load an image (default queue) and import a point cloud (heavy queue)
> update: use separate worker service for each queue

- geoapi/tests/api_tests/test_projects_routes.py
- geoapi/utils/decorators.py
Update project GET so that if a project uuid is incorrect it also returns 404.
> hotfix: return 404 if project uuid is invalid

- geoapi/migrations/versions/20250414_1430-nullify_legacy_tokens.py
- geoapi/services/streetview.py
- geoapi/tests/api_tests/test_streetview_routes.py
https://github.com/TACC-Cloud/geoapi/pull/244 had an error as didn't account for nullified tokens. This PR refactors the logic to instead use a migration that nullifies any existing tokens lacking an expiration date. With that cleanup in place, we can handle expired tokens more cleanly in code going forward.
1. Check unit tests and we'll test on staging
> hotfix: use migration to nullify streetview tokens
