TACC-Cloud/geoapi

- geoapi/tasks/lidar.py
- geoapi/tests/api_tests/test_point_cloud_service.py
- misc/potree/page_template/viewer_template.html
Needed to improve asset panel for point clouds (DES-1371)
> Create potree preview viewer that does not have logo or menu

- geoapi/routes/projects.py
Add logging statements for most of the routes (except for some of the GET routes).
> Add logger statements

- geoapi/services/projects.py
Fixes observable save file path.
Removed parsing statement for `/` path and made sure that import paths always include correct path also wrapped export in try/catch.
1. Ensure that the following work
- Export to root path of MyData
- Export to folder selected path of MyData
- Export to project system
- Create rapid project to both MyData and project system
> Fix observable project import.

- CHANGELOG.md
Make releases and add CHANGELOG.md
* [DES-1951](https://jira.tacc.utexas.edu/browse/DES-1951)
1. Review changelog
2. Review releases on Github (https://github.com/TACC-Cloud/geoapi/releases)
I did not create a release for 2.0
> DES-1951: add changelog file

- geoapi/models/imported_file.py
Autogenerated migration was edited (in #82 ) and this column need to be updated to match that
* [DES-2198](https://jira.tacc.utexas.edu/browse/DES-2198)
> Fix model/migration from DES-2198

- Makefile
Tagging our images with 'latest' tag as using them in some "utitliy/testing" kubernetes pods for troubleshooting.
None
> Publish worker image with 'latest' tag

- CHANGELOG.md
> Make 2.9 release notes

- CHANGELOG.md
> Create v2.10 release notes

- Dockerfile.potree
fix poetry install in worker image (missed in #115)
> hotfix: fix poetry install in worker image

- CHANGELOG.md
> Update changelog for 2.11

- CHANGELOG.md
> Update changelog for v2.12

- CHANGELOG.md
> make v2.13 release

- kube/geoapi.yaml
> hotfix: fix key name for secret

- kube/geoapi.yaml
> hotfix: add missing secrets to worker

- geoapi/db.py
fix db connection issues with pool_pre_ping and pool_reset_on_return.
* [WG-131](https://jira.tacc.utexas.edu/browse/WG-131)
> task/WG-131: fix db connection issues with pool_pre_ping and pool_reset_on_return

- CHANGELOG.md
> Add release notes for 2.14

- CHANGELOG.md
> Make v2.15 release notes

- geoapi/models/point_cloud.py
- geoapi/models/task.py
- geoapi/tasks/external_data.py
- geoapi/utils/decorators.py
Improve (slightly) some point cloud related logging
None
> hotifx: improve logging of point clouds

- geoapi/utils/agave.py
Improve exception and allow GET to have parameters.  This was added to help me debug something.
> hotfix:  improve exception and allow GET to have parameters

- README.md
Update migration section in README.  Text has been updated so that its more clear this is only related to creating new migrations and not about the initial dev setup.
> hotifx: update migration section in README

- CHANGELOG.md
> Update changelog for v2.16

- CHANGELOG.md
Update Changelog for v2.17 release
> Update Changelog for v2.17 release

- devops/hazmapper/README.md
- devops/hazmapper/nginx.conf
add nginx conf for hazmapper.tacc.utexas.edu to devops folder
* [WG-257](https://tacc-main.atlassian.net/browse/WG-275)
> task/WG-275: add nginx conf for hazmapper.tacc.utexas.edu to devops folder

- geoapi/tasks/external_data.py
Improve logging by logging exception if something goes wrong when processing point cloud
* [WG-285](https://tacc-main.atlassian.net/browse/WG-285)
> hotifx: improve logging

- devops/database/docker-compose-database.yml
- devops/docker-compose.local.yml
- devops/docker-compose.test.yml
- devops/geoapi-services/docker-compose.yml
- devops/geoapi-workers/docker-compose.yml
Remove deprecated version in docker-compose
> Hotfix:  Remove deprecated version in docker-compose

- devops/hazmapper/nginx.conf
Update nginx.conf to match hazmapper.tacc.utexas.edu
> hotifx:  Update nginx.conf to match hazmapper.tacc.utexas.edu

- CHANGELOG.md
Update changelog for v2.18 and v.29
> Update CHANGELOG.md for V2.18 and V2.19

- geoapi/models/point_cloud.py
- geoapi/models/users.py
Various very minor logging improvements
> hotfix: improve logging

- geoapi/services/streetview.py
- geoapi/tests/api_tests/test_streetview_routes.py
Fixes handling of tokens that were stored prior to adding `token_expires_at` to the model
None
1. Run unit tests
2. Can retest when deployed to staging
> hotifx: fix nullifying of streetview tokens

- geoapi/routes/auth.py
- geoapi/settings.py
- geoapi/tests/utils_tests/test_client_backend.py
- geoapi/utils/client_backend.py
Enable auth for hazmapper-tmp
* [WG-511](https://tacc-main.atlassian.net/browse/WG-511)
Deployed to staging
1. Test with hazmapper-tmp.tacc.utexas.edu/staging (ensure login works)
2. Test with hazmapper.tacc.utexas.edu/staging (ensure login still works there)
> task/WG-511: enable auth for hazmapper-tmp
